#!/usr/bin/env python3
"""Single source of truth for the flat-memory ABI shared by every backend.

The whole simulation state lives in ONE array of f64 ("M").  The host (JS) writes
input + level data into it, calls advance(dt) and reads state/events back out.
This script emits the index constants for every language so the ports can't drift.
"""
import os, sys

SECTIONS = []          # (name, [fields])   fields -> consecutive indices from 0
def sec(name, fields): SECTIONS.append((name, fields.split()))

# relative body layout shared by the player and every enemy
sec('B', 'X Y VX VY W H GND HX HY')
# player, absolute at P_BASE = 0
sec('P', 'X Y VX VY W H GND HX HY FACE COYOTE BUFFER JUMPS WALLDIR WALLGRACE WALLMEM WALLLOCK '
         'DASHT DASHCD DASHDIR AIRDASH INV DROPT HP MAXHP DEAD DEADT RIDING SAFEX SAFEY SAFET PREVY WASGND')
sec('G', 'TIME COINS KILLS DEATHS SCORE BOSSKILLED BOSSACTIVE FREEZE CHKX CHKY MODE VIEWW RNG LW '
         'DOORON DOORX DOORY0 DOORY1 DOORCLOSED GOALON GOALX GOALY BTRIG BSPECX BSPECY COINSTOTAL '
         'NCOINS NEN NPLT NSH NSPR NCK EVN BOSS SPAWNX SPAWNY ACC STEPS NSPEC')
sec('IN', 'AX JUMPHELD DOWNHELD JUMPPRESS DASHPRESS')
sec('E', 'X Y VX VY W H GND HX HY KIND ALIVE DIR T STOMP OX OY CD HP HP0 STATE ST INV SHOTS')
sec('C', 'KIND X Y GOT R')
sec('PT', 'KIND X X0 TOP TOP0 PREVTOP DX DY W SOLID T STATE TIMER VY')
sec('S', 'X Y VX VY G LIFE R PURPLE SIZE')
sec('SP', 'X Y T')
sec('CK', 'X Y ON')

# (name, count-per-item, max-items) laid out after the fixed header
TABLES = [('EV', 4, 192), ('SPEC', 3, 1200), ('TILE', 1, 320 * 14), ('COIN', 6, 256),
          ('EN', 24, 48), ('PLT', 16, 24), ('SH', 10, 64), ('SPR', 4, 16), ('CKT', 4, 16)]

ENUMS = {
  'SK': 'COIN GEM HEART SLIME BAT SAW TURRET SPRING PLAT_H PLAT_V CRUMBLE CHECK BOSS',
  'EK': 'SLIME BAT SAW TURRET BOSS',
  'BS': 'SLEEP INTRO IDLE JUMP RECOVER SHOOT CHARGE DYING',
  'EV': 'NONE JUMP DOUBLE WALLJUMP LAND DASH COIN GEM HEART KILL HURT DIE SPRING SHOOT CHECK CRUMBLE '
        'BOOM BOSSHIT DOOR PIT RESPAWN COMPLETE BOSSDEAD SHOTHIT BOSSSTART BOSSEXPLODE',
  'CS': 'IDLE SHAKE FALL GONE',
  'MODE': 'PLAY CLEAR TITLE',
}

def layout():
    c = []   # (name, value)
    for name, fields in SECTIONS:
        for i, f in enumerate(fields):
            c.append((f'{name}_{f}', i))
    base = 0
    P_BASE = 0; G_BASE = 48; IN_BASE = 96; base = 104
    assert len(dict(SECTIONS)['P']) <= 48 and len(dict(SECTIONS)['G']) <= 48
    # absolute names for the fixed regions (P_X etc. become absolute)
    out = []
    for name, fields in SECTIONS:
        for i, f in enumerate(fields):
            if name == 'P': out.append((f'P_{f}', P_BASE + i))
            elif name == 'G': out.append((f'G_{f}', G_BASE + i))
            elif name == 'IN': out.append((f'IN_{f}', IN_BASE + i))
            elif name == 'B': out.append((f'B_{f}', i))
            else: out.append((f'{name}_{f}', i))      # relative to their row
    for t, n, mx in TABLES:
        out += [(f'{t}_BASE', base), (f'{t}_N', n), (f'{t}_MAX', mx)]
        base += n * mx
    out.append(('MEM_SIZE', (base + 7) // 8 * 8))
    for e, names in ENUMS.items():
        for i, n in enumerate(names.split()):
            out.append((f'{e}_{n}', i))
    return out

def emit(lang, consts):
    L = []
    for n, v in consts:
        if lang == 'c':      L.append(f'#define {n} {v}')
        elif lang == 'rust': L.append(f'pub const {n}: usize = {v};')
        elif lang == 'zig':  L.append(f'pub const {n}: usize = {v};')
        elif lang == 'go':   L.append(f'const {n} = {v}')
        elif lang == 'nim':  L.append(f'const {n}* = {v}')
        elif lang == 'js':   L.append(f'const {n} = {v};')
        elif lang == 'ml':   L.append(f'let {n.lower()} = {v}')
        elif lang == 'hs':   L.append(f'{n.lower()} :: Int\n{n.lower()} = {v}')
        elif lang == 'fst':  L.append(f'let {n.lower()} : int = {v}')
    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'core')
    consts = layout()
    hdr = 'GENERATED by tools/abi.py - do not edit'
    files = {
      'c/abi.h':        ('c',    f'/* {hdr} */\n'),
      'rust/src/abi.rs':('rust', f'// {hdr}\n#![allow(dead_code)]\n'),
      'zig/abi.zig':    ('zig',  f'// {hdr}\n'),
      'go/abi.go':      ('go',   f'// {hdr}\npackage main\n\n'),
      'nim/abi.nim':    ('nim',  f'# {hdr}\n'),
      'js/abi.js':      ('js',   f'// {hdr}\n'),
      'ocaml/abi.ml':   ('ml',   f'(* {hdr} *)\n'),
      'haskell/Abi.hs': ('hs',   f'-- {hdr}\nmodule Abi where\n\n'),
      'fstar/Abi.fst':  ('fst',  f'(* {hdr} *)\nmodule Abi\n\n'),
    }
    for path, (lang, head) in files.items():
        p = os.path.join(root, path); os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, 'w').write(head + emit(lang, consts))
    print(len(consts), 'constants; MEM_SIZE =', dict(consts)['MEM_SIZE'])
